# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'try4.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1280, 800)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.DefinitionTabs = QtGui.QTabWidget(self.centralwidget)
        self.DefinitionTabs.setGeometry(QtCore.QRect(10, 0, 1085, 306))
        self.DefinitionTabs.setMinimumSize(QtCore.QSize(1085, 282))
        self.DefinitionTabs.setMaximumSize(QtCore.QSize(1085, 2820))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DefinitionTabs.setFont(font)
        self.DefinitionTabs.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.DefinitionTabs.setTabPosition(QtGui.QTabWidget.North)
        self.DefinitionTabs.setTabShape(QtGui.QTabWidget.Triangular)
        self.DefinitionTabs.setIconSize(QtCore.QSize(17, 18))
        self.DefinitionTabs.setElideMode(QtCore.Qt.ElideLeft)
        self.DefinitionTabs.setObjectName(_fromUtf8("DefinitionTabs"))
        self.Joints_tab = QtGui.QWidget()
        self.Joints_tab.setObjectName(_fromUtf8("Joints_tab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.Joints_tab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Joints_table = QtGui.QTableWidget(self.Joints_tab)
        self.Joints_table.setMinimumSize(QtCore.QSize(481, 263))
        self.Joints_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Joints_table.setAutoFillBackground(True)
        self.Joints_table.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Joints_table.setFrameShape(QtGui.QFrame.NoFrame)
        self.Joints_table.setFrameShadow(QtGui.QFrame.Raised)
        self.Joints_table.setLineWidth(3)
        self.Joints_table.setMidLineWidth(13)
        self.Joints_table.setAutoScroll(True)
        self.Joints_table.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.Joints_table.setDragEnabled(True)
        self.Joints_table.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.Joints_table.setAlternatingRowColors(True)
        self.Joints_table.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.Joints_table.setShowGrid(True)
        self.Joints_table.setGridStyle(QtCore.Qt.SolidLine)
        self.Joints_table.setCornerButtonEnabled(True)
        self.Joints_table.setObjectName(_fromUtf8("Joints_table"))
        self.Joints_table.setColumnCount(4)
        self.Joints_table.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.Joints_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Joints_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Joints_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Joints_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Joints_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Joints_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.Joints_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Joints_table.setItem(1, 0, item)
        self.Joints_table.horizontalHeader().setVisible(False)
        self.Joints_table.horizontalHeader().setCascadingSectionResizes(False)
        self.Joints_table.horizontalHeader().setDefaultSectionSize(115)
        self.Joints_table.horizontalHeader().setSortIndicatorShown(False)
        self.Joints_table.horizontalHeader().setStretchLastSection(False)
        self.Joints_table.verticalHeader().setSortIndicatorShown(False)
        self.Joints_table.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.Joints_table)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Add_new_row_joint = QtGui.QPushButton(self.Joints_tab)
        self.Add_new_row_joint.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Add_new_row_joint.setObjectName(_fromUtf8("Add_new_row_joint"))
        self.verticalLayout.addWidget(self.Add_new_row_joint)
        self.Delete_last_row_Joint = QtGui.QPushButton(self.Joints_tab)
        self.Delete_last_row_Joint.setMinimumSize(QtCore.QSize(0, 0))
        self.Delete_last_row_Joint.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Delete_last_row_Joint.setObjectName(_fromUtf8("Delete_last_row_Joint"))
        self.verticalLayout.addWidget(self.Delete_last_row_Joint)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.Insert_row_number_Joint_2 = QtGui.QLineEdit(self.Joints_tab)
        self.Insert_row_number_Joint_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Insert_row_number_Joint_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Insert_row_number_Joint_2.setObjectName(_fromUtf8("Insert_row_number_Joint_2"))
        self.gridLayout_5.addWidget(self.Insert_row_number_Joint_2, 1, 1, 1, 1)
        self.Insert_row_button_Joint = QtGui.QPushButton(self.Joints_tab)
        self.Insert_row_button_Joint.setEnabled(True)
        self.Insert_row_button_Joint.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Insert_row_button_Joint.setObjectName(_fromUtf8("Insert_row_button_Joint"))
        self.gridLayout_5.addWidget(self.Insert_row_button_Joint, 0, 0, 1, 1)
        self.Insert_row_number_Joint = QtGui.QLineEdit(self.Joints_tab)
        self.Insert_row_number_Joint.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Insert_row_number_Joint.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Insert_row_number_Joint.setAlignment(QtCore.Qt.AlignCenter)
        self.Insert_row_number_Joint.setObjectName(_fromUtf8("Insert_row_number_Joint"))
        self.gridLayout_5.addWidget(self.Insert_row_number_Joint, 0, 1, 1, 1)
        self.Delete_row_button_Joint = QtGui.QPushButton(self.Joints_tab)
        self.Delete_row_button_Joint.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Delete_row_button_Joint.setObjectName(_fromUtf8("Delete_row_button_Joint"))
        self.gridLayout_5.addWidget(self.Delete_row_button_Joint, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.DefinitionTabs.addTab(self.Joints_tab, _fromUtf8(""))
        self.Members_tab = QtGui.QWidget()
        self.Members_tab.setObjectName(_fromUtf8("Members_tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Members_tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget_3 = QtGui.QTabWidget(self.Members_tab)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.Member_Def = QtGui.QWidget()
        self.Member_Def.setObjectName(_fromUtf8("Member_Def"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Member_Def)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.MemberTable = QtGui.QTableWidget(self.Member_Def)
        self.MemberTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MemberTable.setAutoFillBackground(True)
        self.MemberTable.setInputMethodHints(QtCore.Qt.ImhNone)
        self.MemberTable.setFrameShape(QtGui.QFrame.NoFrame)
        self.MemberTable.setFrameShadow(QtGui.QFrame.Raised)
        self.MemberTable.setLineWidth(3)
        self.MemberTable.setMidLineWidth(13)
        self.MemberTable.setAutoScroll(True)
        self.MemberTable.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.MemberTable.setDragEnabled(True)
        self.MemberTable.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.MemberTable.setAlternatingRowColors(True)
        self.MemberTable.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.MemberTable.setShowGrid(True)
        self.MemberTable.setGridStyle(QtCore.Qt.SolidLine)
        self.MemberTable.setCornerButtonEnabled(True)
        self.MemberTable.setObjectName(_fromUtf8("MemberTable"))
        self.MemberTable.setColumnCount(15)
        self.MemberTable.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.MemberTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.MemberTable.setItem(0, 0, item)
        self.MemberTable.horizontalHeader().setVisible(False)
        self.MemberTable.horizontalHeader().setCascadingSectionResizes(False)
        self.MemberTable.horizontalHeader().setDefaultSectionSize(66)
        self.MemberTable.horizontalHeader().setSortIndicatorShown(False)
        self.MemberTable.horizontalHeader().setStretchLastSection(False)
        self.MemberTable.verticalHeader().setSortIndicatorShown(False)
        self.MemberTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.MemberTable)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.AISC_database_button = QtGui.QComboBox(self.Member_Def)
        self.AISC_database_button.setMinimumSize(QtCore.QSize(111, 0))
        self.AISC_database_button.setObjectName(_fromUtf8("AISC_database_button"))
        self.AISC_database_button.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.AISC_database_button, 1, 0, 1, 1)
        self.AISC_assign_button = QtGui.QPushButton(self.Member_Def)
        self.AISC_assign_button.setObjectName(_fromUtf8("AISC_assign_button"))
        self.gridLayout_3.addWidget(self.AISC_assign_button, 2, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        spacerItem3 = QtGui.QSpacerItem(600, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.Mem_def_delete = QtGui.QPushButton(self.Member_Def)
        self.Mem_def_delete.setObjectName(_fromUtf8("Mem_def_delete"))
        self.gridLayout_4.addWidget(self.Mem_def_delete, 1, 1, 1, 1)
        self.Mem_def_add = QtGui.QPushButton(self.Member_Def)
        self.Mem_def_add.setObjectName(_fromUtf8("Mem_def_add"))
        self.gridLayout_4.addWidget(self.Mem_def_add, 0, 1, 1, 1)
        self.Insert_after_label = QtGui.QLabel(self.Member_Def)
        self.Insert_after_label.setObjectName(_fromUtf8("Insert_after_label"))
        self.gridLayout_4.addWidget(self.Insert_after_label, 1, 6, 1, 1)
        self.Insert_after_number_mem_def = QtGui.QLineEdit(self.Member_Def)
        self.Insert_after_number_mem_def.setObjectName(_fromUtf8("Insert_after_number_mem_def"))
        self.gridLayout_4.addWidget(self.Insert_after_number_mem_def, 1, 7, 1, 1)
        self.Copy_from_number_mem_def = QtGui.QLineEdit(self.Member_Def)
        self.Copy_from_number_mem_def.setObjectName(_fromUtf8("Copy_from_number_mem_def"))
        self.gridLayout_4.addWidget(self.Copy_from_number_mem_def, 1, 5, 1, 1)
        self.Delete_row_mem_def_button = QtGui.QPushButton(self.Member_Def)
        self.Delete_row_mem_def_button.setObjectName(_fromUtf8("Delete_row_mem_def_button"))
        self.gridLayout_4.addWidget(self.Delete_row_mem_def_button, 1, 2, 1, 1)
        self.Copy_from_label = QtGui.QLabel(self.Member_Def)
        self.Copy_from_label.setObjectName(_fromUtf8("Copy_from_label"))
        self.gridLayout_4.addWidget(self.Copy_from_label, 1, 4, 1, 1)
        self.Insert_row_number_mem_def = QtGui.QLineEdit(self.Member_Def)
        self.Insert_row_number_mem_def.setObjectName(_fromUtf8("Insert_row_number_mem_def"))
        self.gridLayout_4.addWidget(self.Insert_row_number_mem_def, 0, 3, 1, 1)
        self.Insert_row_mem_def_button = QtGui.QPushButton(self.Member_Def)
        self.Insert_row_mem_def_button.setObjectName(_fromUtf8("Insert_row_mem_def_button"))
        self.gridLayout_4.addWidget(self.Insert_row_mem_def_button, 0, 2, 1, 1)
        self.Copy_mem_def_button = QtGui.QPushButton(self.Member_Def)
        self.Copy_mem_def_button.setObjectName(_fromUtf8("Copy_mem_def_button"))
        self.gridLayout_4.addWidget(self.Copy_mem_def_button, 0, 4, 1, 4)
        self.Delete_row_number_mem_def = QtGui.QLineEdit(self.Member_Def)
        self.Delete_row_number_mem_def.setObjectName(_fromUtf8("Delete_row_number_mem_def"))
        self.gridLayout_4.addWidget(self.Delete_row_number_mem_def, 1, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget_3.addTab(self.Member_Def, _fromUtf8(""))
        self.Add_Nodes = QtGui.QWidget()
        self.Add_Nodes.setObjectName(_fromUtf8("Add_Nodes"))
        self.tabWidget_3.addTab(self.Add_Nodes, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget_3)
        self.DefinitionTabs.addTab(self.Members_tab, _fromUtf8(""))
        self.Mem_properties_tab = QtGui.QWidget()
        self.Mem_properties_tab.setObjectName(_fromUtf8("Mem_properties_tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.Mem_properties_tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tableWidget = QtGui.QTableWidget(self.Mem_properties_tab)
        self.tableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.Apply_all_member_properties = QtGui.QPushButton(self.Mem_properties_tab)
        self.Apply_all_member_properties.setObjectName(_fromUtf8("Apply_all_member_properties"))
        self.verticalLayout_3.addWidget(self.Apply_all_member_properties)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        spacerItem5 = QtGui.QSpacerItem(600, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.Delete_last_row_Mem_prop = QtGui.QPushButton(self.Mem_properties_tab)
        self.Delete_last_row_Mem_prop.setObjectName(_fromUtf8("Delete_last_row_Mem_prop"))
        self.gridLayout_7.addWidget(self.Delete_last_row_Mem_prop, 1, 1, 1, 1)
        self.Add_New_Row_Mem_Prop = QtGui.QPushButton(self.Mem_properties_tab)
        self.Add_New_Row_Mem_Prop.setObjectName(_fromUtf8("Add_New_Row_Mem_Prop"))
        self.gridLayout_7.addWidget(self.Add_New_Row_Mem_Prop, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.Mem_properties_tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_7.addWidget(self.label_9, 1, 6, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.Mem_properties_tab)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_7.addWidget(self.lineEdit_8, 1, 7, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.Mem_properties_tab)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_7.addWidget(self.lineEdit_9, 1, 5, 1, 1)
        self.Delete_Row_Number_Mem_Prop = QtGui.QPushButton(self.Mem_properties_tab)
        self.Delete_Row_Number_Mem_Prop.setObjectName(_fromUtf8("Delete_Row_Number_Mem_Prop"))
        self.gridLayout_7.addWidget(self.Delete_Row_Number_Mem_Prop, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.Mem_properties_tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 1, 4, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.Mem_properties_tab)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_7.addWidget(self.lineEdit_10, 0, 3, 1, 1)
        self.Insert_New_Row_Mem_Prop = QtGui.QPushButton(self.Mem_properties_tab)
        self.Insert_New_Row_Mem_Prop.setObjectName(_fromUtf8("Insert_New_Row_Mem_Prop"))
        self.gridLayout_7.addWidget(self.Insert_New_Row_Mem_Prop, 0, 2, 1, 1)
        self.Copy_Mem_Prop = QtGui.QPushButton(self.Mem_properties_tab)
        self.Copy_Mem_Prop.setObjectName(_fromUtf8("Copy_Mem_Prop"))
        self.gridLayout_7.addWidget(self.Copy_Mem_Prop, 0, 4, 1, 4)
        self.lineEdit_11 = QtGui.QLineEdit(self.Mem_properties_tab)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_7.addWidget(self.lineEdit_11, 1, 3, 1, 1)
        self.horizontalLayout_12.addLayout(self.gridLayout_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.DefinitionTabs.addTab(self.Mem_properties_tab, _fromUtf8(""))
        self.B_C_tab = QtGui.QWidget()
        self.B_C_tab.setObjectName(_fromUtf8("B_C_tab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.B_C_tab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.B_C_tab)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.Fixities_table = QtGui.QTableWidget(self.tab)
        self.Fixities_table.setMinimumSize(QtCore.QSize(818, 0))
        self.Fixities_table.setAlternatingRowColors(True)
        self.Fixities_table.setObjectName(_fromUtf8("Fixities_table"))
        self.Fixities_table.setColumnCount(8)
        self.Fixities_table.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.Fixities_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Fixities_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Fixities_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Fixities_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Fixities_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Fixities_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Fixities_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Fixities_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Fixities_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Fixities_table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Fixities_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Fixities_table.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Fixities_table.setItem(1, 7, item)
        self.horizontalLayout_5.addWidget(self.Fixities_table)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.Delete_last_row_spring_2 = QtGui.QPushButton(self.tab)
        self.Delete_last_row_spring_2.setMinimumSize(QtCore.QSize(0, 0))
        self.Delete_last_row_spring_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Delete_last_row_spring_2.setObjectName(_fromUtf8("Delete_last_row_spring_2"))
        self.gridLayout_10.addWidget(self.Delete_last_row_spring_2, 1, 0, 1, 1)
        self.Delete_new_row_button_spring_2 = QtGui.QPushButton(self.tab)
        self.Delete_new_row_button_spring_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Delete_new_row_button_spring_2.setObjectName(_fromUtf8("Delete_new_row_button_spring_2"))
        self.gridLayout_10.addWidget(self.Delete_new_row_button_spring_2, 3, 0, 1, 1)
        self.Insert_new_row_button_spring_2 = QtGui.QPushButton(self.tab)
        self.Insert_new_row_button_spring_2.setEnabled(True)
        self.Insert_new_row_button_spring_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Insert_new_row_button_spring_2.setObjectName(_fromUtf8("Insert_new_row_button_spring_2"))
        self.gridLayout_10.addWidget(self.Insert_new_row_button_spring_2, 2, 0, 1, 1)
        self.Add_new_row_spring_2 = QtGui.QPushButton(self.tab)
        self.Add_new_row_spring_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Add_new_row_spring_2.setObjectName(_fromUtf8("Add_new_row_spring_2"))
        self.gridLayout_10.addWidget(self.Add_new_row_spring_2, 0, 0, 1, 1)
        self.Inser_number_spring_2 = QtGui.QLineEdit(self.tab)
        self.Inser_number_spring_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Inser_number_spring_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Inser_number_spring_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Inser_number_spring_2.setObjectName(_fromUtf8("Inser_number_spring_2"))
        self.gridLayout_10.addWidget(self.Inser_number_spring_2, 2, 1, 1, 1)
        self.Delete_number_spring_2 = QtGui.QLineEdit(self.tab)
        self.Delete_number_spring_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Delete_number_spring_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Delete_number_spring_2.setObjectName(_fromUtf8("Delete_number_spring_2"))
        self.gridLayout_10.addWidget(self.Delete_number_spring_2, 3, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_10)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Shear_panel_table = QtGui.QTableWidget(self.tab_2)
        self.Shear_panel_table.setMinimumSize(QtCore.QSize(618, 0))
        self.Shear_panel_table.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.Shear_panel_table.setObjectName(_fromUtf8("Shear_panel_table"))
        self.Shear_panel_table.setColumnCount(6)
        self.Shear_panel_table.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.Shear_panel_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Shear_panel_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Shear_panel_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Shear_panel_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Shear_panel_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Shear_panel_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Shear_panel_table.setHorizontalHeaderItem(5, item)
        self.horizontalLayout_2.addWidget(self.Shear_panel_table)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.Add_new_row_shear_panel = QtGui.QPushButton(self.tab_2)
        self.Add_new_row_shear_panel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Add_new_row_shear_panel.setObjectName(_fromUtf8("Add_new_row_shear_panel"))
        self.verticalLayout_6.addWidget(self.Add_new_row_shear_panel)
        self.Delete_last_row_shear_panel = QtGui.QPushButton(self.tab_2)
        self.Delete_last_row_shear_panel.setMinimumSize(QtCore.QSize(0, 0))
        self.Delete_last_row_shear_panel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Delete_last_row_shear_panel.setObjectName(_fromUtf8("Delete_last_row_shear_panel"))
        self.verticalLayout_6.addWidget(self.Delete_last_row_shear_panel)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.Inser_number_shear_panel = QtGui.QLineEdit(self.tab_2)
        self.Inser_number_shear_panel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Inser_number_shear_panel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Inser_number_shear_panel.setAlignment(QtCore.Qt.AlignCenter)
        self.Inser_number_shear_panel.setObjectName(_fromUtf8("Inser_number_shear_panel"))
        self.gridLayout_6.addWidget(self.Inser_number_shear_panel, 0, 1, 1, 1)
        self.Delete_number_shear_panel = QtGui.QLineEdit(self.tab_2)
        self.Delete_number_shear_panel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Delete_number_shear_panel.setAlignment(QtCore.Qt.AlignCenter)
        self.Delete_number_shear_panel.setObjectName(_fromUtf8("Delete_number_shear_panel"))
        self.gridLayout_6.addWidget(self.Delete_number_shear_panel, 1, 1, 1, 1)
        self.Insert_new_row_button_shear_panel = QtGui.QPushButton(self.tab_2)
        self.Insert_new_row_button_shear_panel.setEnabled(True)
        self.Insert_new_row_button_shear_panel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Insert_new_row_button_shear_panel.setObjectName(_fromUtf8("Insert_new_row_button_shear_panel"))
        self.gridLayout_6.addWidget(self.Insert_new_row_button_shear_panel, 0, 0, 1, 1)
        self.Delete_new_row_button_shear_panel = QtGui.QPushButton(self.tab_2)
        self.Delete_new_row_button_shear_panel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Delete_new_row_button_shear_panel.setObjectName(_fromUtf8("Delete_new_row_button_shear_panel"))
        self.gridLayout_6.addWidget(self.Delete_new_row_button_shear_panel, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.Discrete_grounded_spring_table = QtGui.QTableWidget(self.tab_3)
        self.Discrete_grounded_spring_table.setMinimumSize(QtCore.QSize(897, 0))
        self.Discrete_grounded_spring_table.setAlternatingRowColors(True)
        self.Discrete_grounded_spring_table.setObjectName(_fromUtf8("Discrete_grounded_spring_table"))
        self.Discrete_grounded_spring_table.setColumnCount(16)
        self.Discrete_grounded_spring_table.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.Discrete_grounded_spring_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Discrete_grounded_spring_table.setHorizontalHeaderItem(15, item)
        self.Discrete_grounded_spring_table.horizontalHeader().setDefaultSectionSize(55)
        self.horizontalLayout_6.addWidget(self.Discrete_grounded_spring_table)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.Delete_last_row_spring = QtGui.QPushButton(self.tab_3)
        self.Delete_last_row_spring.setMinimumSize(QtCore.QSize(0, 0))
        self.Delete_last_row_spring.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Delete_last_row_spring.setObjectName(_fromUtf8("Delete_last_row_spring"))
        self.gridLayout_8.addWidget(self.Delete_last_row_spring, 1, 0, 1, 1)
        self.Delete_new_row_button_spring = QtGui.QPushButton(self.tab_3)
        self.Delete_new_row_button_spring.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Delete_new_row_button_spring.setObjectName(_fromUtf8("Delete_new_row_button_spring"))
        self.gridLayout_8.addWidget(self.Delete_new_row_button_spring, 3, 0, 1, 1)
        self.Insert_new_row_button_spring = QtGui.QPushButton(self.tab_3)
        self.Insert_new_row_button_spring.setEnabled(True)
        self.Insert_new_row_button_spring.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Insert_new_row_button_spring.setObjectName(_fromUtf8("Insert_new_row_button_spring"))
        self.gridLayout_8.addWidget(self.Insert_new_row_button_spring, 2, 0, 1, 1)
        self.Add_new_row_spring = QtGui.QPushButton(self.tab_3)
        self.Add_new_row_spring.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Add_new_row_spring.setObjectName(_fromUtf8("Add_new_row_spring"))
        self.gridLayout_8.addWidget(self.Add_new_row_spring, 0, 0, 1, 1)
        self.Inser_number_spring = QtGui.QLineEdit(self.tab_3)
        self.Inser_number_spring.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Inser_number_spring.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Inser_number_spring.setAlignment(QtCore.Qt.AlignCenter)
        self.Inser_number_spring.setObjectName(_fromUtf8("Inser_number_spring"))
        self.gridLayout_8.addWidget(self.Inser_number_spring, 2, 1, 1, 1)
        self.Delete_number_spring = QtGui.QLineEdit(self.tab_3)
        self.Delete_number_spring.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Delete_number_spring.setAlignment(QtCore.Qt.AlignCenter)
        self.Delete_number_spring.setObjectName(_fromUtf8("Delete_number_spring"))
        self.gridLayout_8.addWidget(self.Delete_number_spring, 3, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_8)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Warping_Release = QtGui.QTableWidget(self.tab_4)
        self.Warping_Release.setObjectName(_fromUtf8("Warping_Release"))
        self.Warping_Release.setColumnCount(3)
        self.Warping_Release.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.Warping_Release.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Warping_Release.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Warping_Release.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Warping_Release.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Warping_Release.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Warping_Release.setItem(0, 2, item)
        self.Warping_Release.horizontalHeader().setDefaultSectionSize(64)
        self.gridLayout.addWidget(self.Warping_Release, 1, 3, 1, 1)
        self.Warping_text = QtGui.QLabel(self.tab_4)
        self.Warping_text.setObjectName(_fromUtf8("Warping_text"))
        self.gridLayout.addWidget(self.Warping_text, 0, 3, 1, 1)
        self.Torsional_Release = QtGui.QTableWidget(self.tab_4)
        self.Torsional_Release.setObjectName(_fromUtf8("Torsional_Release"))
        self.Torsional_Release.setColumnCount(3)
        self.Torsional_Release.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.Torsional_Release.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Torsional_Release.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Torsional_Release.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Torsional_Release.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Torsional_Release.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Torsional_Release.setItem(0, 2, item)
        self.Torsional_Release.horizontalHeader().setDefaultSectionSize(64)
        self.gridLayout.addWidget(self.Torsional_Release, 1, 0, 1, 1)
        self.My_release_text = QtGui.QLabel(self.tab_4)
        self.My_release_text.setObjectName(_fromUtf8("My_release_text"))
        self.gridLayout.addWidget(self.My_release_text, 0, 1, 1, 1)
        self.My_release = QtGui.QTableWidget(self.tab_4)
        self.My_release.setObjectName(_fromUtf8("My_release"))
        self.My_release.setColumnCount(3)
        self.My_release.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.My_release.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.My_release.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.My_release.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.My_release.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.My_release.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.My_release.setItem(0, 2, item)
        self.My_release.horizontalHeader().setDefaultSectionSize(64)
        self.gridLayout.addWidget(self.My_release, 1, 1, 1, 1)
        self.Mz_release = QtGui.QTableWidget(self.tab_4)
        self.Mz_release.setObjectName(_fromUtf8("Mz_release"))
        self.Mz_release.setColumnCount(3)
        self.Mz_release.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.Mz_release.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Mz_release.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Mz_release.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Mz_release.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Mz_release.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Mz_release.setItem(0, 2, item)
        self.Mz_release.horizontalHeader().setDefaultSectionSize(64)
        self.gridLayout.addWidget(self.Mz_release, 1, 2, 1, 1)
        self.Torsional_release_text = QtGui.QLabel(self.tab_4)
        self.Torsional_release_text.setObjectName(_fromUtf8("Torsional_release_text"))
        self.gridLayout.addWidget(self.Torsional_release_text, 0, 0, 1, 1)
        self.Mz_release_text = QtGui.QLabel(self.tab_4)
        self.Mz_release_text.setObjectName(_fromUtf8("Mz_release_text"))
        self.gridLayout.addWidget(self.Mz_release_text, 0, 2, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.tabWidget)
        self.DefinitionTabs.addTab(self.B_C_tab, _fromUtf8(""))
        self.Loading_Tab = QtGui.QWidget()
        self.Loading_Tab.setObjectName(_fromUtf8("Loading_Tab"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.Loading_Tab)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tabWidget_2 = QtGui.QTabWidget(self.Loading_Tab)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.Load_Combinations = QtGui.QWidget()
        self.Load_Combinations.setObjectName(_fromUtf8("Load_Combinations"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.Load_Combinations)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Delete_LC = QtGui.QPushButton(self.Load_Combinations)
        self.Delete_LC.setObjectName(_fromUtf8("Delete_LC"))
        self.gridLayout_2.addWidget(self.Delete_LC, 0, 4, 1, 1)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.Load_Combinations)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_2.addWidget(self.plainTextEdit, 0, 2, 1, 1)
        self.Apply_LC_name = QtGui.QPushButton(self.Load_Combinations)
        self.Apply_LC_name.setObjectName(_fromUtf8("Apply_LC_name"))
        self.gridLayout_2.addWidget(self.Apply_LC_name, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.Load_Combinations)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.label_8 = QtGui.QLabel(self.Load_Combinations)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_7.addWidget(self.label_8)
        self.Load_combination_list = QtGui.QScrollArea(self.Load_Combinations)
        self.Load_combination_list.setMinimumSize(QtCore.QSize(0, 150))
        self.Load_combination_list.setWidgetResizable(True)
        self.Load_combination_list.setObjectName(_fromUtf8("Load_combination_list"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 80, 148))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.Load_combination_list.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.Load_combination_list)
        self.tabWidget_2.addTab(self.Load_Combinations, _fromUtf8(""))
        self.Def_Uni_Load = QtGui.QWidget()
        self.Def_Uni_Load.setObjectName(_fromUtf8("Def_Uni_Load"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.Def_Uni_Load)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.Uniform_loading_table = QtGui.QTableWidget(self.Def_Uni_Load)
        self.Uniform_loading_table.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.Uniform_loading_table.setAlternatingRowColors(True)
        self.Uniform_loading_table.setObjectName(_fromUtf8("Uniform_loading_table"))
        self.Uniform_loading_table.setColumnCount(5)
        self.Uniform_loading_table.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.Uniform_loading_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Uniform_loading_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Uniform_loading_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Uniform_loading_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Uniform_loading_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Uniform_loading_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Uniform_loading_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Uniform_loading_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Uniform_loading_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.Uniform_loading_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Uniform_loading_table.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Uniform_loading_table.setItem(2, 0, item)
        self.Uniform_loading_table.horizontalHeader().setDefaultSectionSize(150)
        self.horizontalLayout_10.addWidget(self.Uniform_loading_table)
        self.tabWidget_2.addTab(self.Def_Uni_Load, _fromUtf8(""))
        self.Def_Point_Loads = QtGui.QWidget()
        self.Def_Point_Loads.setObjectName(_fromUtf8("Def_Point_Loads"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.Def_Point_Loads)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.Point_load_table = QtGui.QTableWidget(self.Def_Point_Loads)
        self.Point_load_table.setMinimumSize(QtCore.QSize(818, 0))
        self.Point_load_table.setAutoFillBackground(False)
        self.Point_load_table.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.Point_load_table.setAlternatingRowColors(True)
        self.Point_load_table.setObjectName(_fromUtf8("Point_load_table"))
        self.Point_load_table.setColumnCount(10)
        self.Point_load_table.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.Point_load_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Point_load_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Point_load_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Point_load_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        self.Point_load_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Point_load_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Point_load_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Point_load_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Point_load_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Point_load_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Point_load_table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Point_load_table.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Point_load_table.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.Point_load_table.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Point_load_table.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Point_load_table.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Point_load_table.setItem(2, 3, item)
        self.Point_load_table.horizontalHeader().setCascadingSectionResizes(True)
        self.Point_load_table.horizontalHeader().setDefaultSectionSize(80)
        self.Point_load_table.horizontalHeader().setMinimumSectionSize(80)
        self.horizontalLayout_7.addWidget(self.Point_load_table)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.Delete_last_row_spring_3 = QtGui.QPushButton(self.Def_Point_Loads)
        self.Delete_last_row_spring_3.setMinimumSize(QtCore.QSize(0, 0))
        self.Delete_last_row_spring_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Delete_last_row_spring_3.setObjectName(_fromUtf8("Delete_last_row_spring_3"))
        self.gridLayout_11.addWidget(self.Delete_last_row_spring_3, 1, 0, 1, 1)
        self.Delete_new_row_button_spring_3 = QtGui.QPushButton(self.Def_Point_Loads)
        self.Delete_new_row_button_spring_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Delete_new_row_button_spring_3.setObjectName(_fromUtf8("Delete_new_row_button_spring_3"))
        self.gridLayout_11.addWidget(self.Delete_new_row_button_spring_3, 3, 0, 1, 1)
        self.Insert_new_row_button_spring_3 = QtGui.QPushButton(self.Def_Point_Loads)
        self.Insert_new_row_button_spring_3.setEnabled(True)
        self.Insert_new_row_button_spring_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Insert_new_row_button_spring_3.setObjectName(_fromUtf8("Insert_new_row_button_spring_3"))
        self.gridLayout_11.addWidget(self.Insert_new_row_button_spring_3, 2, 0, 1, 1)
        self.Add_new_row_spring_3 = QtGui.QPushButton(self.Def_Point_Loads)
        self.Add_new_row_spring_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Add_new_row_spring_3.setObjectName(_fromUtf8("Add_new_row_spring_3"))
        self.gridLayout_11.addWidget(self.Add_new_row_spring_3, 0, 0, 1, 1)
        self.Inser_number_spring_3 = QtGui.QLineEdit(self.Def_Point_Loads)
        self.Inser_number_spring_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Inser_number_spring_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Inser_number_spring_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Inser_number_spring_3.setObjectName(_fromUtf8("Inser_number_spring_3"))
        self.gridLayout_11.addWidget(self.Inser_number_spring_3, 2, 1, 1, 1)
        self.Delete_number_spring_3 = QtGui.QLineEdit(self.Def_Point_Loads)
        self.Delete_number_spring_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Delete_number_spring_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Delete_number_spring_3.setObjectName(_fromUtf8("Delete_number_spring_3"))
        self.gridLayout_11.addWidget(self.Delete_number_spring_3, 3, 1, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_11)
        self.tabWidget_2.addTab(self.Def_Point_Loads, _fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.tabWidget_2)
        self.DefinitionTabs.addTab(self.Loading_Tab, _fromUtf8(""))
        self.toolButton_2 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(20, 320, 78, 22))
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.toolButton = QtGui.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(200, 320, 78, 22))
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionPrint_Preview = QtGui.QAction(MainWindow)
        self.actionPrint_Preview.setObjectName(_fromUtf8("actionPrint_Preview"))
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionView = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/SABRE2_resources/ic_camera_enhance_36pt_2x.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionView.setIcon(icon)
        self.actionView.setObjectName(_fromUtf8("actionView"))
        self.actionDefinition = QtGui.QAction(MainWindow)
        self.actionDefinition.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/SABRE2_resources/ic_list_36pt_2x.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDefinition.setIcon(icon1)
        self.actionDefinition.setObjectName(_fromUtf8("actionDefinition"))
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint_Preview)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionView)
        self.toolBar.addAction(self.actionDefinition)

        self.retranslateUi(MainWindow)
        self.DefinitionTabs.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QObject.connect(self.toolButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.DefinitionTabs.show)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.DefinitionTabs.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.Joints_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Joints_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.Joints_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Joint #", None))
        item = self.Joints_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X", None))
        item = self.Joints_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Y", None))
        item = self.Joints_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Z", None))
        __sortingEnabled = self.Joints_table.isSortingEnabled()
        self.Joints_table.setSortingEnabled(False)
        item = self.Joints_table.item(0, 0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Joints_table.item(1, 0)
        item.setText(_translate("MainWindow", "2", None))
        self.Joints_table.setSortingEnabled(__sortingEnabled)
        self.Add_new_row_joint.setText(_translate("MainWindow", "Add New Row", None))
        self.Delete_last_row_Joint.setText(_translate("MainWindow", "Delete Last Row", None))
        self.Insert_row_number_Joint_2.setText(_translate("MainWindow", "2", None))
        self.Insert_row_button_Joint.setText(_translate("MainWindow", "Insert a New Row After", None))
        self.Insert_row_number_Joint.setText(_translate("MainWindow", "2", None))
        self.Delete_row_button_Joint.setText(_translate("MainWindow", "Delete Row Number", None))
        self.DefinitionTabs.setTabText(self.DefinitionTabs.indexOf(self.Joints_tab), _translate("MainWindow", "Joints", None))
        item = self.MemberTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.MemberTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Member #", None))
        item = self.MemberTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "i", None))
        item = self.MemberTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "j", None))
        item = self.MemberTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "bf1_i", None))
        item = self.MemberTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "tf1_i", None))
        item = self.MemberTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "bf2_i", None))
        item = self.MemberTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "tf2_i", None))
        item = self.MemberTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "bf1_j", None))
        item = self.MemberTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "tf1_j", None))
        item = self.MemberTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "bf2_j", None))
        item = self.MemberTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "tf2_j", None))
        item = self.MemberTable.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "dw_i", None))
        item = self.MemberTable.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "tw_i", None))
        item = self.MemberTable.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "dw_j", None))
        item = self.MemberTable.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "tw_j", None))
        __sortingEnabled = self.MemberTable.isSortingEnabled()
        self.MemberTable.setSortingEnabled(False)
        item = self.MemberTable.item(0, 0)
        item.setText(_translate("MainWindow", "1", None))
        self.MemberTable.setSortingEnabled(__sortingEnabled)
        self.AISC_database_button.setItemText(0, _translate("MainWindow", "AISC Database", None))
        self.AISC_assign_button.setText(_translate("MainWindow", "Assign", None))
        self.Mem_def_delete.setText(_translate("MainWindow", "Delete Last Row", None))
        self.Mem_def_add.setText(_translate("MainWindow", "Add New Row", None))
        self.Insert_after_label.setText(_translate("MainWindow", "Insert After", None))
        self.Delete_row_mem_def_button.setText(_translate("MainWindow", "Delete Row Number", None))
        self.Copy_from_label.setText(_translate("MainWindow", "Copy From", None))
        self.Insert_row_mem_def_button.setText(_translate("MainWindow", "Insert a New Row After", None))
        self.Copy_mem_def_button.setText(_translate("MainWindow", "Copy and Insert", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.Member_Def), _translate("MainWindow", "Member Definition", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.Add_Nodes), _translate("MainWindow", "Add Nodes", None))
        self.DefinitionTabs.setTabText(self.DefinitionTabs.indexOf(self.Members_tab), _translate("MainWindow", "Members", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Member/Segment", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "# of Elements", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "E", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "G", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Density", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fyw", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Fy1", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Fy2", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "29000", None))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "11200", None))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "0.00034028", None))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "50", None))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("MainWindow", "50", None))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("MainWindow", "50", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.Apply_all_member_properties.setText(_translate("MainWindow", "Apply All", None))
        self.Delete_last_row_Mem_prop.setText(_translate("MainWindow", "Delete Last Row", None))
        self.Add_New_Row_Mem_Prop.setText(_translate("MainWindow", "Add New Row", None))
        self.label_9.setText(_translate("MainWindow", "Insert After", None))
        self.Delete_Row_Number_Mem_Prop.setText(_translate("MainWindow", "Delete Row Number", None))
        self.label_10.setText(_translate("MainWindow", "Copy From", None))
        self.Insert_New_Row_Mem_Prop.setText(_translate("MainWindow", "Insert a New Row After", None))
        self.Copy_Mem_Prop.setText(_translate("MainWindow", "Copy and Insert", None))
        self.DefinitionTabs.setTabText(self.DefinitionTabs.indexOf(self.Mem_properties_tab), _translate("MainWindow", "Member Properties", None))
        item = self.Fixities_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Fixities_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.Fixities_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Node #", None))
        item = self.Fixities_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "D1", None))
        item = self.Fixities_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "D2", None))
        item = self.Fixities_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "D3", None))
        item = self.Fixities_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "R1", None))
        item = self.Fixities_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "R2", None))
        item = self.Fixities_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "R3", None))
        item = self.Fixities_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Warping", None))
        __sortingEnabled = self.Fixities_table.isSortingEnabled()
        self.Fixities_table.setSortingEnabled(False)
        item = self.Fixities_table.item(0, 0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Fixities_table.item(1, 0)
        item.setText(_translate("MainWindow", "2", None))
        self.Fixities_table.setSortingEnabled(__sortingEnabled)
        self.Delete_last_row_spring_2.setText(_translate("MainWindow", "Delete Last \n"
" Row", None))
        self.Delete_new_row_button_spring_2.setText(_translate("MainWindow", "Delete Row \n"
"Number", None))
        self.Insert_new_row_button_spring_2.setText(_translate("MainWindow", "Insert a New \n"
" Row After", None))
        self.Add_new_row_spring_2.setText(_translate("MainWindow", "Add New\n"
" Row", None))
        self.Inser_number_spring_2.setText(_translate("MainWindow", "2", None))
        self.Delete_number_spring_2.setText(_translate("MainWindow", "2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Fixities", None))
        item = self.Shear_panel_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Shear_panel_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Member #", None))
        item = self.Shear_panel_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Location", None))
        item = self.Shear_panel_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Node i", None))
        item = self.Shear_panel_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Node j", None))
        item = self.Shear_panel_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stiffness", None))
        item = self.Shear_panel_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status", None))
        self.Add_new_row_shear_panel.setText(_translate("MainWindow", "Add New Row", None))
        self.Delete_last_row_shear_panel.setText(_translate("MainWindow", "Delete Last Row", None))
        self.Inser_number_shear_panel.setText(_translate("MainWindow", "2", None))
        self.Delete_number_shear_panel.setText(_translate("MainWindow", "2", None))
        self.Insert_new_row_button_shear_panel.setText(_translate("MainWindow", "Insert a New \n"
"Row After", None))
        self.Delete_new_row_button_shear_panel.setText(_translate("MainWindow", "Delete Row \n"
"Number", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Shear Panels", None))
        item = self.Discrete_grounded_spring_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Node #", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Location", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "D1", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "D2", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "D3", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Status", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "R1", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Staus", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "R2", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Status", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "R3", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Status", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Warping", None))
        item = self.Discrete_grounded_spring_table.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Status", None))
        self.Delete_last_row_spring.setText(_translate("MainWindow", "Delete Last \n"
" Row", None))
        self.Delete_new_row_button_spring.setText(_translate("MainWindow", "Delete Row \n"
"Number", None))
        self.Insert_new_row_button_spring.setText(_translate("MainWindow", "Insert a New \n"
" Row After", None))
        self.Add_new_row_spring.setText(_translate("MainWindow", "Add New\n"
" Row", None))
        self.Inser_number_spring.setText(_translate("MainWindow", "2", None))
        self.Delete_number_spring.setText(_translate("MainWindow", "2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Discrete Grounded Springs", None))
        item = self.Warping_Release.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Warping_Release.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Element #", None))
        item = self.Warping_Release.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node i", None))
        item = self.Warping_Release.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Node j", None))
        __sortingEnabled = self.Warping_Release.isSortingEnabled()
        self.Warping_Release.setSortingEnabled(False)
        self.Warping_Release.setSortingEnabled(__sortingEnabled)
        self.Warping_text.setText(_translate("MainWindow", "Warping Releases", None))
        item = self.Torsional_Release.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Torsional_Release.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Element #", None))
        item = self.Torsional_Release.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node i", None))
        item = self.Torsional_Release.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Node j", None))
        __sortingEnabled = self.Torsional_Release.isSortingEnabled()
        self.Torsional_Release.setSortingEnabled(False)
        self.Torsional_Release.setSortingEnabled(__sortingEnabled)
        self.My_release_text.setText(_translate("MainWindow", "Flexural Releases of Continuity, My ", None))
        item = self.My_release.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.My_release.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Element #", None))
        item = self.My_release.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node i", None))
        item = self.My_release.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Node j", None))
        __sortingEnabled = self.My_release.isSortingEnabled()
        self.My_release.setSortingEnabled(False)
        self.My_release.setSortingEnabled(__sortingEnabled)
        item = self.Mz_release.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Mz_release.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Element #", None))
        item = self.Mz_release.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node i", None))
        item = self.Mz_release.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Node j", None))
        __sortingEnabled = self.Mz_release.isSortingEnabled()
        self.Mz_release.setSortingEnabled(False)
        self.Mz_release.setSortingEnabled(__sortingEnabled)
        self.Torsional_release_text.setText(_translate("MainWindow", "Torsional Releases of Continuity, Mx", None))
        self.Mz_release_text.setText(_translate("MainWindow", "Flexural Releases of Continuity, Mz", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Flexural and / or Warping Releases", None))
        self.DefinitionTabs.setTabText(self.DefinitionTabs.indexOf(self.B_C_tab), _translate("MainWindow", "Boundary Conditions", None))
        self.Delete_LC.setText(_translate("MainWindow", "Delete", None))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Enter Load Combination Name", None))
        self.Apply_LC_name.setText(_translate("MainWindow", "Apply", None))
        self.label_7.setText(_translate("MainWindow", "Name of Load Combination:", None))
        self.label_8.setText(_translate("MainWindow", "Defined Load Combinations:", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Load_Combinations), _translate("MainWindow", "Load Combinations", None))
        item = self.Uniform_loading_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Uniform_loading_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.Uniform_loading_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.Uniform_loading_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Member / Segment #", None))
        item = self.Uniform_loading_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Load Combination Name", None))
        item = self.Uniform_loading_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "wx", None))
        item = self.Uniform_loading_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "wy", None))
        item = self.Uniform_loading_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "wz", None))
        __sortingEnabled = self.Uniform_loading_table.isSortingEnabled()
        self.Uniform_loading_table.setSortingEnabled(False)
        item = self.Uniform_loading_table.item(0, 0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Uniform_loading_table.item(1, 0)
        item.setText(_translate("MainWindow", "2", None))
        item = self.Uniform_loading_table.item(2, 0)
        item.setText(_translate("MainWindow", "3", None))
        self.Uniform_loading_table.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Def_Uni_Load), _translate("MainWindow", "Define Uniform Loads", None))
        item = self.Point_load_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Point_load_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.Point_load_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.Point_load_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Node #", None))
        item = self.Point_load_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "LC Name", None))
        item = self.Point_load_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Load Height", None))
        item = self.Point_load_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "alpha", None))
        item = self.Point_load_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fx", None))
        item = self.Point_load_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fy", None))
        item = self.Point_load_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Fz", None))
        item = self.Point_load_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Mx", None))
        item = self.Point_load_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "My", None))
        item = self.Point_load_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Mz", None))
        __sortingEnabled = self.Point_load_table.isSortingEnabled()
        self.Point_load_table.setSortingEnabled(False)
        item = self.Point_load_table.item(0, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.Point_load_table.item(1, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.Point_load_table.item(2, 3)
        item.setText(_translate("MainWindow", "0", None))
        self.Point_load_table.setSortingEnabled(__sortingEnabled)
        self.Delete_last_row_spring_3.setText(_translate("MainWindow", "Delete Last \n"
" Row", None))
        self.Delete_new_row_button_spring_3.setText(_translate("MainWindow", "Delete Row \n"
"Number", None))
        self.Insert_new_row_button_spring_3.setText(_translate("MainWindow", "Insert a New \n"
" Row After", None))
        self.Add_new_row_spring_3.setText(_translate("MainWindow", "Add New\n"
" Row", None))
        self.Inser_number_spring_3.setText(_translate("MainWindow", "2", None))
        self.Delete_number_spring_3.setText(_translate("MainWindow", "2", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Def_Point_Loads), _translate("MainWindow", "Define Point Loads", None))
        self.DefinitionTabs.setTabText(self.DefinitionTabs.indexOf(self.Loading_Tab), _translate("MainWindow", "Loading", None))
        self.toolButton_2.setText(_translate("MainWindow", "Show", None))
        self.toolButton.setText(_translate("MainWindow", "Hide", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As", None))
        self.actionPrint_Preview.setText(_translate("MainWindow", "Print Preview", None))
        self.actionPrint.setText(_translate("MainWindow", "Print", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionView.setText(_translate("MainWindow", "View", None))
        self.actionView.setToolTip(_translate("MainWindow", "View options", None))
        self.actionDefinition.setText(_translate("MainWindow", "Definition", None))
        self.actionDefinition.setToolTip(_translate("MainWindow", "Define Member &/ or Frame", None))

import SABRE2_resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

