# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'try4.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1280, 800)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.DefinitionTabs = QtGui.QTabWidget(self.centralwidget)
        self.DefinitionTabs.setGeometry(QtCore.QRect(10, 450, 1031, 306))
        self.DefinitionTabs.setMinimumSize(QtCore.QSize(1031, 282))
        self.DefinitionTabs.setMaximumSize(QtCore.QSize(10000, 2820))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DefinitionTabs.setFont(font)
        self.DefinitionTabs.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.DefinitionTabs.setTabPosition(QtGui.QTabWidget.North)
        self.DefinitionTabs.setTabShape(QtGui.QTabWidget.Triangular)
        self.DefinitionTabs.setIconSize(QtCore.QSize(17, 18))
        self.DefinitionTabs.setElideMode(QtCore.Qt.ElideLeft)
        self.DefinitionTabs.setObjectName(_fromUtf8("DefinitionTabs"))
        self.Joints_tab = QtGui.QWidget()
        self.Joints_tab.setObjectName(_fromUtf8("Joints_tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Joints_tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.NodeTable = QtGui.QTableWidget(self.Joints_tab)
        self.NodeTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NodeTable.setAutoFillBackground(True)
        self.NodeTable.setInputMethodHints(QtCore.Qt.ImhNone)
        self.NodeTable.setFrameShape(QtGui.QFrame.NoFrame)
        self.NodeTable.setFrameShadow(QtGui.QFrame.Raised)
        self.NodeTable.setLineWidth(3)
        self.NodeTable.setMidLineWidth(13)
        self.NodeTable.setSizeAdjustPolicy(QtGui.QAbstractScrollArea.AdjustToContents)
        self.NodeTable.setAutoScroll(True)
        self.NodeTable.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.NodeTable.setDragEnabled(True)
        self.NodeTable.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.NodeTable.setAlternatingRowColors(True)
        self.NodeTable.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.NodeTable.setShowGrid(True)
        self.NodeTable.setGridStyle(QtCore.Qt.SolidLine)
        self.NodeTable.setCornerButtonEnabled(True)
        self.NodeTable.setObjectName(_fromUtf8("NodeTable"))
        self.NodeTable.setColumnCount(4)
        self.NodeTable.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.NodeTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.NodeTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.NodeTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.NodeTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.NodeTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.NodeTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.NodeTable.setItem(0, 0, item)
        self.NodeTable.horizontalHeader().setVisible(False)
        self.NodeTable.horizontalHeader().setCascadingSectionResizes(False)
        self.NodeTable.horizontalHeader().setDefaultSectionSize(115)
        self.NodeTable.horizontalHeader().setSortIndicatorShown(False)
        self.NodeTable.horizontalHeader().setStretchLastSection(True)
        self.NodeTable.verticalHeader().setSortIndicatorShown(False)
        self.NodeTable.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.NodeTable)
        spacerItem = QtGui.QSpacerItem(480, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.DefinitionTabs.addTab(self.Joints_tab, _fromUtf8(""))
        self.Members_tab = QtGui.QWidget()
        self.Members_tab.setObjectName(_fromUtf8("Members_tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Members_tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.MemberTable = QtGui.QTableWidget(self.Members_tab)
        self.MemberTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MemberTable.setAutoFillBackground(True)
        self.MemberTable.setInputMethodHints(QtCore.Qt.ImhNone)
        self.MemberTable.setFrameShape(QtGui.QFrame.NoFrame)
        self.MemberTable.setFrameShadow(QtGui.QFrame.Raised)
        self.MemberTable.setLineWidth(3)
        self.MemberTable.setMidLineWidth(13)
        self.MemberTable.setSizeAdjustPolicy(QtGui.QAbstractScrollArea.AdjustToContents)
        self.MemberTable.setAutoScroll(True)
        self.MemberTable.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.MemberTable.setDragEnabled(True)
        self.MemberTable.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.MemberTable.setAlternatingRowColors(True)
        self.MemberTable.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.MemberTable.setShowGrid(True)
        self.MemberTable.setGridStyle(QtCore.Qt.SolidLine)
        self.MemberTable.setCornerButtonEnabled(True)
        self.MemberTable.setObjectName(_fromUtf8("MemberTable"))
        self.MemberTable.setColumnCount(15)
        self.MemberTable.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.MemberTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.MemberTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.MemberTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.MemberTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.MemberTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MemberTable.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.MemberTable.setItem(0, 0, item)
        self.MemberTable.horizontalHeader().setVisible(False)
        self.MemberTable.horizontalHeader().setCascadingSectionResizes(False)
        self.MemberTable.horizontalHeader().setDefaultSectionSize(66)
        self.MemberTable.horizontalHeader().setSortIndicatorShown(False)
        self.MemberTable.horizontalHeader().setStretchLastSection(False)
        self.MemberTable.verticalHeader().setSortIndicatorShown(False)
        self.MemberTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.MemberTable)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(800, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButton_2 = QtGui.QPushButton(self.Members_tab)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_4.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.Members_tab)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.Members_tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 6, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.Members_tab)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_4.addWidget(self.lineEdit_4, 1, 7, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.Members_tab)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_4.addWidget(self.lineEdit_3, 1, 5, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.Members_tab)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_4.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.Members_tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 1, 4, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.Members_tab)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_4.addWidget(self.lineEdit, 0, 3, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.Members_tab)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_4.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.Members_tab)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_4.addWidget(self.pushButton_5, 0, 4, 1, 4)
        self.lineEdit_2 = QtGui.QLineEdit(self.Members_tab)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_4.addWidget(self.lineEdit_2, 1, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.DefinitionTabs.addTab(self.Members_tab, _fromUtf8(""))
        self.Mem_properties_tab = QtGui.QWidget()
        self.Mem_properties_tab.setObjectName(_fromUtf8("Mem_properties_tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Mem_properties_tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tableWidget = QtGui.QTableWidget(self.Mem_properties_tab)
        self.tableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_6 = QtGui.QPushButton(self.Mem_properties_tab)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.DefinitionTabs.addTab(self.Mem_properties_tab, _fromUtf8(""))
        self.B_C_tab = QtGui.QWidget()
        self.B_C_tab.setObjectName(_fromUtf8("B_C_tab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.B_C_tab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.B_C_tab)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tableWidget_2 = QtGui.QTableWidget(self.tab)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(1, 7, item)
        self.horizontalLayout_5.addWidget(self.tableWidget_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tableWidget_3 = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_3.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_6.addWidget(self.tableWidget_3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tableWidget_4 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_4.setAlternatingRowColors(True)
        self.tableWidget_4.setObjectName(_fromUtf8("tableWidget_4"))
        self.tableWidget_4.setColumnCount(8)
        self.tableWidget_4.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_4.setHorizontalHeaderItem(7, item)
        self.horizontalLayout_7.addWidget(self.tableWidget_4)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Warping_Release = QtGui.QTableWidget(self.tab_4)
        self.Warping_Release.setObjectName(_fromUtf8("Warping_Release"))
        self.Warping_Release.setColumnCount(3)
        self.Warping_Release.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.Warping_Release.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Warping_Release.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Warping_Release.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Warping_Release.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Warping_Release.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Warping_Release.setItem(0, 2, item)
        self.Warping_Release.horizontalHeader().setDefaultSectionSize(64)
        self.gridLayout.addWidget(self.Warping_Release, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.Torsional_Release = QtGui.QTableWidget(self.tab_4)
        self.Torsional_Release.setObjectName(_fromUtf8("Torsional_Release"))
        self.Torsional_Release.setColumnCount(3)
        self.Torsional_Release.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.Torsional_Release.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Torsional_Release.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Torsional_Release.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Torsional_Release.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Torsional_Release.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Torsional_Release.setItem(0, 2, item)
        self.Torsional_Release.horizontalHeader().setDefaultSectionSize(64)
        self.gridLayout.addWidget(self.Torsional_Release, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.My_release = QtGui.QTableWidget(self.tab_4)
        self.My_release.setObjectName(_fromUtf8("My_release"))
        self.My_release.setColumnCount(3)
        self.My_release.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.My_release.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.My_release.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.My_release.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.My_release.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.My_release.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.My_release.setItem(0, 2, item)
        self.My_release.horizontalHeader().setDefaultSectionSize(64)
        self.gridLayout.addWidget(self.My_release, 1, 1, 1, 1)
        self.Mz_release = QtGui.QTableWidget(self.tab_4)
        self.Mz_release.setObjectName(_fromUtf8("Mz_release"))
        self.Mz_release.setColumnCount(3)
        self.Mz_release.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.Mz_release.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Mz_release.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Mz_release.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Mz_release.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Mz_release.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.Mz_release.setItem(0, 2, item)
        self.Mz_release.horizontalHeader().setDefaultSectionSize(64)
        self.gridLayout.addWidget(self.Mz_release, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.tabWidget)
        self.DefinitionTabs.addTab(self.B_C_tab, _fromUtf8(""))
        self.Loading_Tab = QtGui.QWidget()
        self.Loading_Tab.setObjectName(_fromUtf8("Loading_Tab"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.Loading_Tab)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tabWidget_2 = QtGui.QTabWidget(self.Loading_Tab)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.Load_Combinations = QtGui.QWidget()
        self.Load_Combinations.setObjectName(_fromUtf8("Load_Combinations"))
        self.gridLayout_2 = QtGui.QGridLayout(self.Load_Combinations)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_7 = QtGui.QLabel(self.Load_Combinations)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.Load_Combinations)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_2.addWidget(self.lineEdit_5, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.Load_Combinations)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.Load_Combinations)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 981, 166))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 2, 0, 1, 2)
        self.tabWidget_2.addTab(self.Load_Combinations, _fromUtf8(""))
        self.Def_Uni_Load = QtGui.QWidget()
        self.Def_Uni_Load.setObjectName(_fromUtf8("Def_Uni_Load"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.Def_Uni_Load)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.tableWidget_9 = QtGui.QTableWidget(self.Def_Uni_Load)
        self.tableWidget_9.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.tableWidget_9.setAlternatingRowColors(True)
        self.tableWidget_9.setObjectName(_fromUtf8("tableWidget_9"))
        self.tableWidget_9.setColumnCount(5)
        self.tableWidget_9.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_9.setItem(0, 1, item)
        self.tableWidget_9.horizontalHeader().setDefaultSectionSize(150)
        self.horizontalLayout_10.addWidget(self.tableWidget_9)
        self.tabWidget_2.addTab(self.Def_Uni_Load, _fromUtf8(""))
        self.Def_Point_Loads = QtGui.QWidget()
        self.Def_Point_Loads.setObjectName(_fromUtf8("Def_Point_Loads"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.Def_Point_Loads)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.tableWidget_10 = QtGui.QTableWidget(self.Def_Point_Loads)
        self.tableWidget_10.setAutoFillBackground(False)
        self.tableWidget_10.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.tableWidget_10.setAlternatingRowColors(True)
        self.tableWidget_10.setObjectName(_fromUtf8("tableWidget_10"))
        self.tableWidget_10.setColumnCount(10)
        self.tableWidget_10.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(9, item)
        self.tableWidget_10.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_10.horizontalHeader().setDefaultSectionSize(96)
        self.tableWidget_10.horizontalHeader().setMinimumSectionSize(80)
        self.horizontalLayout_11.addWidget(self.tableWidget_10)
        self.tabWidget_2.addTab(self.Def_Point_Loads, _fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.tabWidget_2)
        self.DefinitionTabs.addTab(self.Loading_Tab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.DefinitionTabs.setCurrentIndex(4)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.NodeTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.NodeTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.NodeTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Joint #", None))
        item = self.NodeTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X", None))
        item = self.NodeTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Y", None))
        item = self.NodeTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Z", None))
        __sortingEnabled = self.NodeTable.isSortingEnabled()
        self.NodeTable.setSortingEnabled(False)
        self.NodeTable.setSortingEnabled(__sortingEnabled)
        self.DefinitionTabs.setTabText(self.DefinitionTabs.indexOf(self.Joints_tab), _translate("MainWindow", "Joints", None))
        item = self.MemberTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.MemberTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.MemberTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.MemberTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.MemberTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.MemberTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Member #", None))
        item = self.MemberTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "i", None))
        item = self.MemberTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "j", None))
        item = self.MemberTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "bf1_i", None))
        item = self.MemberTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "tf1_i", None))
        item = self.MemberTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "bf2_i", None))
        item = self.MemberTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "tf2_i", None))
        item = self.MemberTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "bf1_j", None))
        item = self.MemberTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "tf1_j", None))
        item = self.MemberTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "bf2_j", None))
        item = self.MemberTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "tf2_j", None))
        item = self.MemberTable.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "dw_i", None))
        item = self.MemberTable.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "tw_i", None))
        item = self.MemberTable.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "dw_j", None))
        item = self.MemberTable.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "tw_j", None))
        __sortingEnabled = self.MemberTable.isSortingEnabled()
        self.MemberTable.setSortingEnabled(False)
        self.MemberTable.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("MainWindow", "Delete Last Row", None))
        self.pushButton.setText(_translate("MainWindow", "Add New Row", None))
        self.label_2.setText(_translate("MainWindow", "Insert After", None))
        self.pushButton_3.setText(_translate("MainWindow", "Delete Row Number", None))
        self.label.setText(_translate("MainWindow", "Copy From", None))
        self.pushButton_4.setText(_translate("MainWindow", "Insert a New Row After", None))
        self.pushButton_5.setText(_translate("MainWindow", "Copy and Insert", None))
        self.DefinitionTabs.setTabText(self.DefinitionTabs.indexOf(self.Members_tab), _translate("MainWindow", "Members", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Member/Segment", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "# of Elements", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "E", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "G", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Density", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fyw", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Fy1", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Fy2", None))
        self.pushButton_6.setText(_translate("MainWindow", "Apply All", None))
        self.DefinitionTabs.setTabText(self.DefinitionTabs.indexOf(self.Mem_properties_tab), _translate("MainWindow", "Member Properties", None))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Node #", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "D1", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "D2", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "D3", None))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "R1", None))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "R2", None))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "R3", None))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Warping", None))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Fixities", None))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Member #", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Node i", None))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Node j", None))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stiffness", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Shear Panels", None))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Node #", None))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "D1", None))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "D2", None))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "D3", None))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "R1", None))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "R2", None))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "R3", None))
        item = self.tableWidget_4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Warping", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Discrete Grounded Springs", None))
        item = self.Warping_Release.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Warping_Release.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Element #", None))
        item = self.Warping_Release.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node i", None))
        item = self.Warping_Release.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Node j", None))
        __sortingEnabled = self.Warping_Release.isSortingEnabled()
        self.Warping_Release.setSortingEnabled(False)
        self.Warping_Release.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("MainWindow", "Warping Releases", None))
        item = self.Torsional_Release.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Torsional_Release.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Element #", None))
        item = self.Torsional_Release.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node i", None))
        item = self.Torsional_Release.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Node j", None))
        __sortingEnabled = self.Torsional_Release.isSortingEnabled()
        self.Torsional_Release.setSortingEnabled(False)
        self.Torsional_Release.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "Flexural Releases of Continuity, My ", None))
        item = self.My_release.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.My_release.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Element #", None))
        item = self.My_release.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node i", None))
        item = self.My_release.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Node j", None))
        __sortingEnabled = self.My_release.isSortingEnabled()
        self.My_release.setSortingEnabled(False)
        self.My_release.setSortingEnabled(__sortingEnabled)
        item = self.Mz_release.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.Mz_release.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Element #", None))
        item = self.Mz_release.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node i", None))
        item = self.Mz_release.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Node j", None))
        __sortingEnabled = self.Mz_release.isSortingEnabled()
        self.Mz_release.setSortingEnabled(False)
        self.Mz_release.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "Torsional Releases of Continuity, Mx", None))
        self.label_5.setText(_translate("MainWindow", "Flexural Releases of Continuity, Mz", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Flexural and / or Warping Releases", None))
        self.DefinitionTabs.setTabText(self.DefinitionTabs.indexOf(self.B_C_tab), _translate("MainWindow", "Boundary Conditions", None))
        self.label_7.setText(_translate("MainWindow", "Name of Load Combination:", None))
        self.lineEdit_5.setText(_translate("MainWindow", "Enter Load Combination Name Here!", None))
        self.label_8.setText(_translate("MainWindow", "Defined Load Combinations:", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Load_Combinations), _translate("MainWindow", "Load Combinations", None))
        item = self.tableWidget_9.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_9.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_9.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_9.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Member / Segment #", None))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Load Combination Name", None))
        item = self.tableWidget_9.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "wx", None))
        item = self.tableWidget_9.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "wy", None))
        item = self.tableWidget_9.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "wz", None))
        __sortingEnabled = self.tableWidget_9.isSortingEnabled()
        self.tableWidget_9.setSortingEnabled(False)
        self.tableWidget_9.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Def_Uni_Load), _translate("MainWindow", "Define Uniform Loads", None))
        item = self.tableWidget_10.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_10.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_10.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_10.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Node #", None))
        item = self.tableWidget_10.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "LC Name", None))
        item = self.tableWidget_10.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Load Height", None))
        item = self.tableWidget_10.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "alpha", None))
        item = self.tableWidget_10.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fx", None))
        item = self.tableWidget_10.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fy", None))
        item = self.tableWidget_10.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Fz", None))
        item = self.tableWidget_10.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Mx", None))
        item = self.tableWidget_10.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "My", None))
        item = self.tableWidget_10.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Mz", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Def_Point_Loads), _translate("MainWindow", "Define Point Loads", None))
        self.DefinitionTabs.setTabText(self.DefinitionTabs.indexOf(self.Loading_Tab), _translate("MainWindow", "Loading", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

