function SABRE2Table(pn_panel,pt_title_name,fim_infor_name,ptable_type_subpanel,...
   ptable_type_text,ptable_node_subpanel,pdesign_text,pdesign_edit,punit_text,punit_edit,ptable_node_text,ptable_node,ptable_wsection_text,...
   ptable_wsection_edit,ptable_set,ptable_wsname_edit,ptable_seg_subpanel,...
   ptable_seg_text,ptable_seg,ptable_brac_subpanel,ptable_brac_text,ptable_addbracing,...
   ptable_remove_edit,ptable_removebracing,ptable_app_subpanel,ptable_apply,...
   ptable_cancel,ap_type_text,ap_jval_subpanel,ap_jval_text,ap_jval_buttongroup,...
   ap_jval_on_radiobutton,ap_jval_off_radiobutton,ap_AISC_subpanel,ap_AISC_text,...
   ap_AISC_buttongroup,ap_AISC_on_radiobutton,ap_AISC_off_radiobutton,ap_bracket_subpanel,...
   ap_bracket_text,ap_cv_buttongroup,ap_cv_on_radiobutton,ap_cv_off_radiobutton,...
   ap_jeong_text,ap_brent_text,ap_jeong_edit,ap_brent_edit,ap_2nd_subpanel,...
   ap_2nd_text,ap_da_text,ap_da_buttongroup,ap_da_on_radiobutton,ap_da_off_radiobutton,...
   am3_type_text,am4_type_text,am6_type_text,res_subpanel,res_text,recba_gamma_text,...
   recba_scale_text,recba_gamma_edit,recba_Scale_edit,recba_tau_text,recba_tau_diagram,...
   auto_type_text,auto_modelname_text,auto_modelnum_text,auto_modelname_edit,auto_modelnum_edit,...
   auto_lin_apply,auto_nonlin_apply)

% Developed by Woo Yong Jeong.
% Date : 12/01/2012.
% ************************************************************************
% *****************              VISIBLE              ********************
% ************************************************************************
set(pn_panel,'Visible','on')
% *************** Title
set(pt_title_name,'Visible','off')
% *************** About
set(fim_infor_name,'Visible','off')

% *************** Visible off for Modeling S
% *** sub panel1
set(ptable_type_subpanel,'Visible','on')
set(ptable_type_text,'Visible','on')
% *** sub panel2
set(ptable_node_subpanel,'Visible','on')
set(ptable_node_text,'Visible','on');
set(ptable_node,'Visible','on');
set([ptable_wsection_text,ptable_wsection_edit,ptable_set,ptable_wsname_edit],'Visible','on');
set([pdesign_text,pdesign_edit,punit_text,punit_edit],'Visible','on');
% *** sub panel3
set(ptable_seg_subpanel,'Visible','on');
set(ptable_seg_text,'Visible','on');
set(ptable_seg,'Visible','on')
% *** sub panel4
set(ptable_brac_subpanel,'Visible','on');
set(ptable_brac_text,'Visible','on');
set(ptable_addbracing,'Visible','on');
set(ptable_remove_edit,'Visible','on');
set(ptable_removebracing,'Visible','on');
% *** sub panel5
set(ptable_app_subpanel,'Visible','on');
set([ptable_apply,ptable_cancel],'Visible','on'); 
% *************** Visible off for Modeling E


% *************** Visible off for ANALYSIS PARAMETERS S
% *** sub panel1
set(ap_type_text,'Visible','off')
% *** sub panel2
set([ap_jval_subpanel,ap_jval_text,ap_jval_buttongroup,ap_jval_on_radiobutton,ap_jval_off_radiobutton],'Visible','off');
% *** sub panel3
set([ap_AISC_subpanel,ap_AISC_text,ap_AISC_buttongroup,ap_AISC_on_radiobutton,ap_AISC_off_radiobutton],'Visible','off');
% *** sub panel4
set([ap_bracket_subpanel,ap_bracket_text,ap_cv_buttongroup,ap_cv_on_radiobutton,ap_cv_off_radiobutton],'Visible','off');
set([ap_jeong_text,ap_brent_text,ap_jeong_edit,ap_brent_edit],'Visible','off');
% *** sub panel5
set([ap_2nd_subpanel,ap_2nd_text,ap_da_text,ap_da_buttongroup,ap_da_on_radiobutton,ap_da_off_radiobutton],'Visible','off');
% *************** Visible off for ANALYSIS PARAMETERS E

% *************** Visible off for Elastic Linear Buckling S
% *** sub panel1
set(am3_type_text,'Visible','off')
% *************** Visible off for Elastic Linear Buckling E

% *************** Visible off for Inelastic Linear Buckling S
% *** sub panel1
set(am4_type_text,'Visible','off')
% *************** Visible off for Inelastic Linear Buckling E

% *************** Visible off for Inelastic Nonlinear Buckling S
% *** sub panel1
set(am6_type_text,'Visible','off')
% *************** Visible off for Inelastic Nonlinear Buckling E

% *************** Visible off for Results S
% *** sub panel1
set(res_subpanel,'Visible','off')
set([res_text,recba_gamma_text,recba_scale_text],'Visible','off');
set([recba_gamma_edit,recba_Scale_edit],'Visible','off');
set([recba_tau_text,recba_tau_diagram],'Visible','off');  
% *************** Visible off for Results E

% *************** Visible off for Batch Mode S
% *** sub panel1
set(auto_type_text,'Visible','off')
% *** sub panel2
set([auto_modelname_text,auto_modelnum_text,auto_modelname_edit,auto_modelnum_edit,...
   auto_lin_apply,auto_nonlin_apply],'Visible','off');
% *************** Visible off for Batch Mode E


% Set pre-definded database
filename1='AISCSTEEL.mat';
Sectiondata=load(fullfile(filename1));
SECTION=Sectiondata.SECTION;
TYPE=Sectiondata.TYPE;
set(ptable_wsection_edit,'String',num2str(TYPE))

% Get table data
G_getdata=get(ptable_node,'Data');

if isempty(G_getdata(2,1)) ...
   || isempty(G_getdata(3,1)) ...
   || isempty(G_getdata(4,1)) ...
   || isempty(G_getdata(5,1)) ...
   || isempty(G_getdata(6,1)) ...
   || isempty(G_getdata(7,1))...
   || isempty(G_getdata(2,end)) ...
   || isempty(G_getdata(3,end)) ...
   || isempty(G_getdata(4,end)) ...
   || isempty(G_getdata(5,end)) ...
   || isempty(G_getdata(6,end)) ...
   || isempty(G_getdata(7,end))...    
   || isnan(G_getdata(2,1)) ...
   || isnan(G_getdata(3,1)) ...
   || isnan(G_getdata(4,1)) ...
   || isnan(G_getdata(5,1)) ...
   || isnan(G_getdata(6,1)) ...
   || isnan(G_getdata(7,1))...
   || isnan(G_getdata(2,end)) ...
   || isnan(G_getdata(3,end)) ...
   || isnan(G_getdata(4,end)) ...
   || isnan(G_getdata(5,end)) ...
   || isnan(G_getdata(6,end)) ...
   || isnan(G_getdata(7,end))...
   || G_getdata(2,1) <= 0 ...
   || G_getdata(3,1) <= 0 ...  
   || G_getdata(4,1) <= 0 ...
   || G_getdata(5,1) <= 0 ...     
   || G_getdata(6,1) <= 0 ...
   || G_getdata(7,1) <= 0 ...     
   || G_getdata(2,end) <= 0 ...
   || G_getdata(3,end) <= 0 ...  
   || G_getdata(4,end) <= 0 ...
   || G_getdata(5,end) <= 0 ...     
   || G_getdata(6,end) <= 0 ...
   || G_getdata(7,end) <= 0      
set(ptable_wsname_edit,'String','');    
else

   dunit=get(punit_edit,'Value');
   for i=1:(length(SECTION(:,1)))
      if isequal(dunit,1)
         if isequal(SECTION(i,1),G_getdata(2,1)) && isequal(SECTION(i,2),G_getdata(3,1)) ... 
               && isequal(SECTION(i,3),G_getdata(4,1)) && isequal(SECTION(i,4),G_getdata(5,1)) ...
               && isequal(round(SECTION(i,5)*10^5)/10^5,round( ( G_getdata(6,1)  + G_getdata(3,1) + G_getdata(5,1)  )*10^5)/10^5) ...
               && isequal(SECTION(i,6),G_getdata(7,1)) ...
               && isequal(SECTION(i,1),G_getdata(2,end)) && isequal(SECTION(i,2),G_getdata(3,end)) ...
               && isequal(SECTION(i,3),G_getdata(4,end)) && isequal(SECTION(i,4),G_getdata(5,end)) ...
               && isequal(round(SECTION(i,5)*10^5)/10^5,round( ( G_getdata(6,end)  + G_getdata(3,end) + G_getdata(5,end)  )*10^5)/10^5) ...
               && isequal(SECTION(i,6),G_getdata(7,end)) ... 
               && isequal(round(SECTION(i,7)*10^5)/10^5,round( ( G_getdata(2,1)*G_getdata(3,1) ...
               +G_getdata(4,1)*G_getdata(5,1)+G_getdata(6,1)*G_getdata(7,1)  +G_getdata(8,1)  )*10^5)/10^5) ...            
               && isequal(round(SECTION(i,7)*10^5)/10^5,round( ( G_getdata(2,end)*G_getdata(3,end) ...
               +G_getdata(4,end)*G_getdata(5,end)+G_getdata(6,end)*G_getdata(7,end)  +G_getdata(8,end)  )*10^5)/10^5) 

            set(ptable_wsname_edit,'String',num2str(TYPE((i+1),:)));
               break;

         else
            set(ptable_wsname_edit,'String','');
         end 
      elseif isequal(dunit,2)
         if isequal(SECTION(i,1)*2.54,G_getdata(2,1)) && isequal(SECTION(i,2)*2.54,G_getdata(3,1)) ... 
               && isequal(SECTION(i,3)*2.54,G_getdata(4,1)) && isequal(SECTION(i,4)*2.54,G_getdata(5,1)) ...
               && isequal(round((SECTION(i,5)*2.54)*10^5)/10^5,round( ( G_getdata(6,1)  + G_getdata(3,1) + G_getdata(5,1)  )*10^5)/10^5) ...
               && isequal(SECTION(i,6)*2.54,G_getdata(7,1)) ...
               && isequal(SECTION(i,1)*2.54,G_getdata(2,end)) && isequal(SECTION(i,2)*2.54,G_getdata(3,end)) ...
               && isequal(SECTION(i,3)*2.54,G_getdata(4,end)) && isequal(SECTION(i,4)*2.54,G_getdata(5,end)) ...
               && isequal(round((SECTION(i,5)*2.54)*10^5)/10^5,round( ( G_getdata(6,end)  + G_getdata(3,end) + G_getdata(5,end)  )*10^5)/10^5) ...
               && isequal(SECTION(i,6)*2.54,G_getdata(7,end)) ... 
               && isequal(round((SECTION(i,7)*2.54*2.54)*10^5)/10^5,round( ( G_getdata(2,1)*G_getdata(3,1) ...
               +G_getdata(4,1)*G_getdata(5,1)+G_getdata(6,1)*G_getdata(7,1)  +G_getdata(8,1)  )*10^5)/10^5) ...            
               && isequal(round((SECTION(i,7)*2.54*2.54)*10^5)/10^5,round( ( G_getdata(2,end)*G_getdata(3,end) ...
               +G_getdata(4,end)*G_getdata(5,end)+G_getdata(6,end)*G_getdata(7,end)  +G_getdata(8,end)  )*10^5)/10^5) 

            set(ptable_wsname_edit,'String',num2str(TYPE((i+1),:)));
               break;

         else
            set(ptable_wsname_edit,'String','');
         end          
      else
      end
   end

end
set( gca, 'Units', 'normalized', 'Position', [0 0 0.8 1] );  

end
