all: ../qtwidgets/dockwidget_icons.py ../qtwidgets/eclipsedocks_icons.py ../qtwidgets/lineedit_icons.py ../qtwidgets/findwidget_icons.py


../qtwidgets/dockwidget_icons.py: dockwidget_icons.qrc
		    pyrcc4 dockwidget_icons.qrc > ../qtwidgets/dockwidget_icons.py


../qtwidgets/eclipsedocks_icons.py: eclipsedocks_icons.qrc
		    pyrcc4 eclipsedocks_icons.qrc > ../qtwidgets/eclipsedocks_icons.py


../qtwidgets/lineedit_icons.py: lineedit_icons.qrc
		    pyrcc4 lineedit_icons.qrc > ../qtwidgets/lineedit_icons.py


../qtwidgets/findwidget_icons.py: findwidget_icons.qrc
		    pyrcc4 findwidget_icons.qrc > ../qtwidgets/findwidget_icons.py

